/**
 * LZW Image Compression Engine - Decompressor
 * Part of the Academic LZW Image Compression Analyzer project.
 * 
 * This module implements a standard LZW decompression algorithm.
 * It reads the custom binary format generated by the compressor (containing
 * the "LZW2" magic header and metadata), reconstructs the dictionary of 16-bit
 * codes, and decompresses it back to the original Uint8Array.
 */

export interface DecompressionResult {
  originalData: Uint8Array;
  mode: "pixel" | "file";
  filename: string;
  originalSize: number;
  width?: number;
  height?: number;
}

/**
 * Decompresses an LZW-encoded Uint8Array file back to its original state.
 */
export function decompressLZW(compressedData: Uint8Array): DecompressionResult {
  if (compressedData.length < 10) {
    throw new Error("Invalid LZW file: payload is too short to contain a valid header.");
  }

  // 1. Verify Magic Header "LZW2"
  if (
    compressedData[0] !== 76 || // L
    compressedData[1] !== 90 || // Z
    compressedData[2] !== 87 || // W
    compressedData[3] !== 50    // 2
  ) {
    throw new Error("Invalid LZW file: Magic header 'LZW2' not found.");
  }

  // 2. Parse Mode
  const modeByte = compressedData[4];
  const mode: "pixel" | "file" = modeByte === 80 ? "pixel" : "file"; // 'P' or 'B'

  // 3. Parse Filename
  const filenameLength = compressedData[5];
  const filenameOffset = 6;
  const sizeOffset = filenameOffset + filenameLength;

  if (compressedData.length < sizeOffset + 4) {
    throw new Error("Invalid LZW file: Header is truncated.");
  }

  const textDecoder = new TextDecoder();
  const filenameBytes = compressedData.slice(filenameOffset, sizeOffset);
  const filename = textDecoder.decode(filenameBytes);

  // 4. Parse Original Size
  const view = new DataView(compressedData.buffer, compressedData.byteOffset, compressedData.byteLength);
  const originalSize = view.getUint32(sizeOffset, true);

  let width: number | undefined;
  let height: number | undefined;
  let codesOffset = sizeOffset + 4;

  if (mode === "pixel") {
    if (compressedData.length < codesOffset + 8) {
      throw new Error("Invalid LZW file: Pixel metadata header is truncated.");
    }
    width = view.getUint32(codesOffset, true);
    height = view.getUint32(codesOffset + 4, true);
    codesOffset += 8;
  }

  // 5. Parse 16-bit Code Stream
  const remainingBytes = compressedData.length - codesOffset;
  if (remainingBytes % 2 !== 0) {
    throw new Error("Invalid LZW file: Code stream size must be a multiple of 2 bytes.");
  }

  const numCodes = remainingBytes / 2;
  const codes = new Uint16Array(numCodes);
  for (let i = 0; i < numCodes; i++) {
    codes[i] = view.getUint16(codesOffset + i * 2, true);
  }

  if (codes.length === 0) {
    return {
      originalData: new Uint8Array(0),
      mode,
      filename,
      originalSize,
      width,
      height,
    };
  }

  // 6. LZW Decompression Core
  // Initialize dictionary mapping numeric codes (0-65535) to their byte sequences.
  // Each entry is a Uint8Array representing the decompressed bytes for that code.
  const dictionary = new Map<number, Uint8Array>();
  for (let i = 0; i < 256; i++) {
    dictionary.set(i, new Uint8Array([i]));
  }

  let nextCode = 256;
  const MAX_CODE = 65535;

  // Track output chunks and compute size
  const chunks: Uint8Array[] = [];
  let totalOutputLength = 0;

  // LZW initialization
  let oldCode = codes[0];
  let currentString = dictionary.get(oldCode);

  if (!currentString) {
    throw new Error(`Invalid LZW compressed stream: Initial code ${oldCode} is out of bounds.`);
  }

  chunks.push(currentString);
  totalOutputLength += currentString.length;

  let firstCharOfString = currentString[0];

  for (let i = 1; i < codes.length; i++) {
    const code = codes[i];
    let entry: Uint8Array;

    if (dictionary.has(code)) {
      entry = dictionary.get(code)!;
    } else if (code === nextCode) {
      // Special LZW case: Code is not yet in dictionary, meaning it is W + K + W.
      // Reconstruct it from oldCode + first char of oldCode.
      const previousString = dictionary.get(oldCode)!;
      entry = new Uint8Array(previousString.length + 1);
      entry.set(previousString, 0);
      entry[previousString.length] = firstCharOfString;
    } else {
      throw new Error(`LZW Decompression error: Unknown code encountered: ${code}`);
    }

    chunks.push(entry);
    totalOutputLength += entry.length;
    firstCharOfString = entry[0];

    // Add new entry to the dictionary (if space remains)
    if (nextCode <= MAX_CODE) {
      const previousString = dictionary.get(oldCode)!;
      const newEntry = new Uint8Array(previousString.length + 1);
      newEntry.set(previousString, 0);
      newEntry[previousString.length] = firstCharOfString;
      dictionary.set(nextCode, newEntry);
      nextCode++;
    }

    oldCode = code;
  }

  // 7. Flatten Output Chunks
  const originalData = new Uint8Array(totalOutputLength);
  let offset = 0;
  for (const chunk of chunks) {
    originalData.set(chunk, offset);
    offset += chunk.length;
  }

  // Double check decompressed data matches headers
  if (originalData.length !== originalSize) {
    console.warn(
      `Decompressed size (${originalData.length}) does not match original size in header (${originalSize}).`
    );
  }

  return {
    originalData,
    mode,
    filename,
    originalSize,
    width,
    height,
  };
}
